[book]
authors = ["Artem Goncharov"]
language = "en"
src = "."
title = "CloudMon metrics processor"

[build]
build-dir = "../docs"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.linkcheck]

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/gtema/cloudmon-metrics"

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true

[output.html.fold]
enable = true
level = 1
